#!/bin/sh
#
# Start GPIO initialization
#

KMOD_PATH=/lib/modules/3.10.14__isvp_swan_1.0__/ingenic


start() {
    printf "Start GPIO initialization"
    insmod ${KMOD_PATH/%\//}/gpio.ko

    for PIN in $(seq 57 58); do
        echo ${PIN} >/proc/jz/claim/gpio
        # echo ${PIN} > /sys/class/gpio/export
        # echo out > /sys/class/gpio/gpio${PIN}/direction
        # echo 0 > /sys/class/gpio/gpio${PIN}/value
    done
}

pingpong () {
    echo 0 > /sys/class/gpio/gpio57/value
    echo 1 > /sys/class/gpio/gpio58/value
    sleep 0.5
    echo 1 > /sys/class/gpio/gpio57/value
    echo 0 > /sys/class/gpio/gpio58/value
    sleep 0.5
    echo 0 > /sys/class/gpio/gpio57/value
    echo 0 > /sys/class/gpio/gpio58/value
}


case "$1" in
    start)
        start
        pingpong
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

