#!/bin/bash
#
# OpenIPC (c) | version 2022.08.31

# Autoupdate COMPOSER repo
# Remove old building folder (full rebuild)
# Download OpenIPC repo
# Copy files from Projects Overlay
# Build Firmware
# Copy Kernel and Rootfs to TFTP server

RELEASE=""
PROJECT="$1"
PROJECT="${PROJECT:=t31_vixand}"
TFTPSRV="root@172.17.32.17:/mnt/bigger-2tb/Rotator/TFTP"
OUTTIME=$(date +"%Y%m%d")

echo_c() {
    # 31 red, 32 green, 33 yellow, 34 blue, 35 magenta, 36 cyan, 37 white, 38 grey
    t="\e[1;$1m$2\e[0m" || t="$2"
    echo -e "$t"
}

2tftp() {
    echo_c 32 "\nStart transferring files to the TFTP server ...\n"
    scp -r $@ ${TFTPSRV}
}




echo_c 32 "\nAttention, let's start working on the ${PROJECT} project ...\n"
git pull
rm -rf Firmware
git clone --depth=1 https://github.com/OpenIPC/firmware.git Firmware
cp -afv Projects/${PROJECT}/* Firmware
cd Firmware
./building.sh ${PROJECT}
echo_c 35 "\nYou can get the new assembled firmware components here:\n"
tree -C output/images
2tftp output/images/rootfs.squashfs.*  output/images/uImage.*
mkdir -p ../Output/${PROJECT}_
cp -av output/images/rootfs.squashfs.*  output/images/uImage.* ../Output/${PROJECT}_${OUTTIME}
echo_c 35 "\nRollback to home ...\n"
cd -


# tree -L 1 Projects
