#!/bin/bash

LANG=C 
BTIME="/tmp/btime"
RESULT="hi3518ev200_lite"


cd ../../openipc
pwd


echo "The start-stop times for build ${RESULT}" >${BTIME}
date >>${BTIME}
make BOARD=${RESULT} distclean
make BOARD=${RESULT} all
date >>${BTIME}
cat ${BTIME}