#!/bin/bash

cd ../../openipc
pwd


rm -rf \
    output/per-package/alsa-utils \
    output/build/alsa-utils-* \

BOARD=msc313e_lite_baresip make br-alsa-utils-{dirclean,rebuild}


rm -rf \
    output/per-package/libre-openipc \
    output/per-package/librem-openipc \
    output/per-package/baresip-openipc \
    output/build/libre-openipc-* \
    output/build/librem-openipc-* \
    output/build/baresip-openipc-*

BOARD=msc313e_lite_baresip make br-baresip-openipc-{dirclean,rebuild}
